language: java
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script: mvn clean test -DisTest=true -Dcompile-to-commit=true

after_success:
  - ./tools/update_version.sh
  - mvn clean cobertura:cobertura coveralls:report